name: Gomsong
title: LSLAB
description: LSLAB is LostSaga wiki project, provided by Gomsong.
tags:
  - wiki
  - lostsaga
  - kls
  - lso
  - gomsong
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: LostSaga Medal
    url: /ls-medal
  - title: LostSaga KeysViewer
    url: /lskv
email: sjw000324@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id